name: xiaoxia
description: Ur GF.

publish_to: 'none' # Remove this line if you are publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0 # 用于国际化支持
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  device_info_plus: ^3.2.0
  shared_preferences: ^2.0.6
  provider: ^6.0.0
  flutter_sound: ^8.5.0
  path_provider: ^2.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/background_sh.png
    - assets/background_sh.jpg
    - assets/user_avatar.png
    - assets/user_avatar.jpg
    - assets/system_avatar.png
    - assets/system_avatar_sh.png
    - assets/xiaoxia.png
    - assets/shihan.png
    - assets/cover.png
    - assets/blue.jpg

