import random

def get_topic(rel_flag=False):
    topics = [
        "Weekend Plans",
        "Movie Recommendations",
        "Reading Insights",
        "Travel Stories",
        "Music Sharing",
        "Childhood Fun",
        "Food Exploration",
        "Daily Exercise",
        "Trying New Skills",
        "Holiday Celebrations",
        "Ideal Job",
        "Admired People",
        "Embarrassing Experiences",
        "Achievements",
        "Favorite Season",
        "Local Features",
        "Skill Improvement",
        "Fears",
        "Happy Memories",
        "Wishes for Change",
        "Superpower Dreams",
        "Historical Periods",
        "Famous Stories",
        "Party Planning",
        "Social Issues",
        "Pet Stories",
        "Food Preparation",
        "Language Learning",
        "Hiking Experiences",
        "Car Choices",
        "Fashion Style",
        "Cultural Exploration",
        "Art Appreciation",
        "Social Participation",
        "Sports Challenges",
        "Inventions and Ideas",
        "Space Dreams",
        "Historical Mysteries",
        "Competition Experiences",
        "Team Spirit",
        "Volunteer Actions",
        "Habit Improvement",
        "Travel Plans",
        "Playing Instruments",
        "Sports Passion",
        "Concert Experiences",
        "Virtual Reality",
        "Civilization Exploration",
        "Natural Wonders",
        "Science Experiments",
        "Space Exploration",
        "Ancient Life",
        "Daily Life Tips",
        "Healthy Living",
        "Personal Finance",
        "Home Decoration",
        "Parent-Child Activities",
        "Time Management",
        "Stress Relief Methods",
        "Interpersonal Relationships",
        "Personal Growth",
        "Career Development",
        "Educational Views",
        "Tech Trends",
        "Eco-Friendly Living",
        "Internet Trends",
        "Book Recommendations",
        "Movie Discussions",
        "Music Charts",
        "Art Exhibitions",
        "Cultural Festivals",
        "Community Activities",
        "Charity Activities",
        "Healthy Eating",
        "Personal Hobbies",
        "Life Fun"
    ]
    
    relationship_topics = [
        "Communication Skills in Love",
        "Building Trust",
        "Conflict Resolution",
        "Maintaining Personal Space",
        "Ways to Show Love",
        "Sustaining Long-term Relationships",
        "Importance of Shared Interests",
        "Financial Planning in Love",
        "Meaning of Commitment",
        "Boundaries in Male-Female Friendships",
        "Compromise and Sacrifice in Love",
        "Ways to Build Trust",
        "Intimacy in Love",
        "Balancing Work and Love",
        "Overcoming Cultural Differences",
        "Setting Shared Goals",
        "Value Compatibility and Conflicts",
        "Facing Challenges in Love",
        "Self-Growth and Love Relationships",
        "Loyalty in Love",
        "Maintaining Novelty",
        "Handling Family Issues",
        "Role Distribution in Love",
        "Providing Emotional Support",
        "Uncertainty in Love",
        "Recognizing Trust Issues",
        "Differences in Male-Female Communication",
        "Holiday Celebration Traditions and Innovations",
        "Enhancing Emotional Connections",
        "Adapting to Personal Growth and Changes",
        "Cultivating Responsibility",
        "Balancing Trust and Transparency",
        "Coping with Separation",
        "Planning a Shared Future",
        "Mutual Understanding and Support",
        "Establishing Common Language",
        "Identifying and Solving Problems",
        "Ways to Express Emotions",
        "Building a Sense of Security",
        "The Art of Time Management",
        "Opportunities for Partner Growth",
        "Importance of Mental Support",
        "Coordinating Personal Goals and Love Relationships",
        "Maintaining Trust and Honesty",
        "Sustaining Passion",
        "Practicing Mutual Respect",
        "Overcoming Communication Barriers",
        "Balancing Emotional Dependency",
        "Balancing Personal Life and Love",
        "Combining Trust and Independence",
        "Cultivating Shared Interests",
        "Deepening Emotional Communication",
        "Positively Handling Disappointment",
        "Increasing Trust and Understanding",
        "Mutual Support and Encouragement",
        "Emotional Communication Skills",
        "Handling Differences of Opinion",
        "Maintaining Trust and Loyalty"
    ]
    
    return random.choice(topics) if not rel_flag else random.choice(relationship_topics)
